name: "merge-values"
version: "0.5.0"
usage: "unittest for helm charts"
description: "Helm Merge Values is a plugin to combine one or more Helm values files and zero or more value overrides."
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-merge-values"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh"
